-- Old Testament - Law
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'Law'), 'GEN', 1, 50);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'Law'), 'EXO', 2, 40);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'Law'), 'LEV', 3, 27);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'Law'), 'NUM', 4, 36);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'Law'), 'DEU', 5, 34);

-- Old Testament - History
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'History'), 'JOS', 6, 24);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'History'), 'JDG', 7, 21);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'History'), 'RUT', 8, 4);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'History'), '1SA', 9, 31);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'History'), '2SA', 10, 24);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'History'), '1KI', 11, 22);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'History'), '2KI', 12, 25);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'History'), '1CH', 13, 29);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'History'), '2CH', 14, 36);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'History'), 'EZR', 15, 10);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'History'), 'NEH', 16, 13);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'History'), 'EST', 17, 10);

-- Old Testament - Poetry
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'Poetry'), 'JOB', 18, 42);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'Poetry'), 'PSA', 19, 150);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'Poetry'), 'PRO', 20, 31);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'Poetry'), 'ECC', 21, 12);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'Poetry'), 'SNG', 22, 8);

-- Old Testament - Prophecy (Major & Minor)
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'Prophecy'), 'ISA', 23, 66);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'Prophecy'), 'JER', 24, 52);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'Prophecy'), 'LAM', 25, 5);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'Prophecy'), 'EZK', 26, 48);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'Prophecy'), 'DAN', 27, 12);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'Prophecy'), 'HOS', 28, 14);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'Prophecy'), 'JOL', 29, 3);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'Prophecy'), 'AMO', 30, 9);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'Prophecy'), 'OBA', 31, 1);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'Prophecy'), 'JON', 32, 4);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'Prophecy'), 'MIC', 33, 7);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'Prophecy'), 'NAM', 34, 3);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'Prophecy'), 'HAB', 35, 3);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'Prophecy'), 'ZEP', 36, 3);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'Prophecy'), 'HAG', 37, 2);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'Prophecy'), 'ZEC', 38, 14);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'Old Testament'), (SELECT category_pk FROM category WHERE category_name = 'Prophecy'), 'MAL', 39, 4);

-- New Testament - Gospel
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'New Testament'), (SELECT category_pk FROM category WHERE category_name = 'Gospel'), 'MAT', 40, 28);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'New Testament'), (SELECT category_pk FROM category WHERE category_name = 'Gospel'), 'MRK', 41, 16);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'New Testament'), (SELECT category_pk FROM category WHERE category_name = 'Gospel'), 'LUK', 42, 24);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'New Testament'), (SELECT category_pk FROM category WHERE category_name = 'Gospel'), 'JHN', 43, 21);

-- New Testament - History
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'New Testament'), (SELECT category_pk FROM category WHERE category_name = 'History'), 'ACT', 44, 28);

-- New Testament - Epistle
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'New Testament'), (SELECT category_pk FROM category WHERE category_name = 'Epistle'), 'ROM', 45, 16);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'New Testament'), (SELECT category_pk FROM category WHERE category_name = 'Epistle'), '1CO', 46, 16);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'New Testament'), (SELECT category_pk FROM category WHERE category_name = 'Epistle'), '2CO', 47, 13);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'New Testament'), (SELECT category_pk FROM category WHERE category_name = 'Epistle'), 'GAL', 48, 6);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'New Testament'), (SELECT category_pk FROM category WHERE category_name = 'Epistle'), 'EPH', 49, 6);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'New Testament'), (SELECT category_pk FROM category WHERE category_name = 'Epistle'), 'PHP', 50, 4);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'New Testament'), (SELECT category_pk FROM category WHERE category_name = 'Epistle'), 'COL', 51, 4);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'New Testament'), (SELECT category_pk FROM category WHERE category_name = 'Epistle'), '1TH', 52, 5);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'New Testament'), (SELECT category_pk FROM category WHERE category_name = 'Epistle'), '2TH', 53, 3);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'New Testament'), (SELECT category_pk FROM category WHERE category_name = 'Epistle'), '1TI', 54, 6);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'New Testament'), (SELECT category_pk FROM category WHERE category_name = 'Epistle'), '2TI', 55, 4);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'New Testament'), (SELECT category_pk FROM category WHERE category_name = 'Epistle'), 'TIT', 56, 3);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'New Testament'), (SELECT category_pk FROM category WHERE category_name = 'Epistle'), 'PHM', 57, 1);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'New Testament'), (SELECT category_pk FROM category WHERE category_name = 'Epistle'), 'HEB', 58, 13);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'New Testament'), (SELECT category_pk FROM category WHERE category_name = 'Epistle'), 'JAS', 59, 5);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'New Testament'), (SELECT category_pk FROM category WHERE category_name = 'Epistle'), '1PE', 60, 5);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'New Testament'), (SELECT category_pk FROM category WHERE category_name = 'Epistle'), '2PE', 61, 3);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'New Testament'), (SELECT category_pk FROM category WHERE category_name = 'Epistle'), '1JN', 62, 5);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'New Testament'), (SELECT category_pk FROM category WHERE category_name = 'Epistle'), '2JN', 63, 1);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'New Testament'), (SELECT category_pk FROM category WHERE category_name = 'Epistle'), '3JN', 64, 1);
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'New Testament'), (SELECT category_pk FROM category WHERE category_name = 'Epistle'), 'JUD', 65, 1);

-- New Testament - Prophecy
INSERT INTO book_details (testament_fk, category_fk, book_global_id, book_number, chapter_count) VALUES ((SELECT testament_pk FROM testament WHERE testament_name = 'New Testament'), (SELECT category_pk FROM category WHERE category_name = 'Prophecy'), 'REV', 66, 22);